export const LaptopDes = "The Satellite Pro C40 is dressed to impress, with a distinguished dark blue exterior and contemporary design. Weighing just 1.55kg and measuring in at a slender 18.9mm, its the perfect companion for life on the go. It also boasts a 15.5-hour battery life*, so you can enjoy a full work or study day away from mains power."

export const ProcessorDes = "Brand - Intel, Model - Intel Core i3 12100F, Cpu Cooler (Included) - PCG 2020C, Code-Name - Alder Lake, Generation - 12th Gen, Base Frequency - 3.30 GHz, Turbo Frequency Max. - 4.30 GHz, Core - 4, Threads - 8, Smart Cache - 12MB, L2 Cache - 5MB, Lithography - Intel 7, Memory Max. - 128GB, Memory Type - DDR4-3200, DDR5-4800, Memory Channels - 2, Sockets Supported - LGA1700, Others - Processor Base Power: 58W"

export const MonitorDes = "Brand - Lenovo, Model - Lenovo D20-20, Series - Regular, Shape - Widescreen, Display Size (Inch) - 19.5 Inch, Display Type - WXGA+ WLED Display, Panel Type - IPS, Panel Surface - Flat, Borderless - No, Touch Screen - No, Display Resolution - 1440 x 900, Aspect Ratio - 16:10, Pixels Per Inch (PPI) - 87 PPI, Display Surface - Anti-Glare, Maximum Brightness (cd/m2) - 250 cd/m2, Contrast Ratio - 1000:1, Refresh Rate (Hz) - 60Hz, Color Gamut / Color Space - 72% NTSC (CIE 1931)"

export const SSDDes = "OCPC Solid-State Drives (SSD) will make your system more responsive so it boots quicker, loads applications faster and shuts down faster. Solid-state drives are the next evolution of PC storage and run faster, quieter and cooler than the aging technology inside hard drives. With no moving parts, SSDs are also more durable and more reliable than hard drives."

export const RamDes = "Stable and compatible, Netac Basic SO DDR4. Original chips improve the performance of computer. Selected original chips, strict inspection process, 8-layer PCB board, stable performance. Excellent compatibility: Memory products have passed the motherboard compatibility test of mainstream brands on the market, ensure the stability of the system for along time. Gold-plated craft gold finger: Gold plating process, stronger conductivity and corrosion resistance."

export const MotherboardDes = "Intel H470 AORUS Motherboard with Direct 11+1 Phases Digital VRM Design, Comprehensive Thermal Solution with Enlarged Surface Heatsink, Dual Ultra-Fast NVMe PCIe 3.0 x4 M.2 with Thermal Guards, Intel WiFi 6 802.11ax, Intel 2.5GbE LAN, USB 3.2 Gen2 Type-C ,RGB FUSION 2.0,Supports 10th Gen Intel Core Series Processors,Dual Channel Non-ECC Unbuffered DDR4, 4 DIMMs,Direct 11+1 Phases Digital VRM Solution,Advanced Thermal Design with Enlarged Surface Heatsink,Smart Fan 5 Features Multiple Temperature Sensors and Hybrid Fan Headers"